# Site settings
title:          "못읽겠조 팀블로그"
description:    "2020 충남대 하계 모각코 [못읽겠조] 블로그"
baseurl:        ""
url:            "https://mogakco2020.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         LeeSuJeong
  url:          https://realcrystal.github.io
  email:        realcrystal98@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed


# Custom vars
  repo: https://github.com/mogakco2020/mogakco2020.github.io



# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5



# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale


